source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'sass-rails', '~>4.0.5'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'clusterpoint'
gem 'rails_12factor'
gem 'rest-client', '~> 2.0.0.rc1'
gem 'pry-rails'